
exports.seed = function (knex) {
  // Inserts seed entries
  return knex('etype_actornv3').insert([
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'CIN', desc: 'Cinema' },
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'CMP', desc: 'Camping' },
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'EDU', desc: 'Local Educacional' },
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'GAM', desc: 'Jogos' },
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'STD', desc: 'Área de Esporte/Estádio' },
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'SWM', desc: 'Piscina' },
    { actor: 'BEV', actornv2: 'ASR', actornv3: 'THE', desc: 'Teatro' },

    { actor: 'BEV', actornv2: 'IND', actornv3: 'APT', desc: 'Aeroporto' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'FRM', desc: 'Fazenda' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'HRB', desc: 'Porto' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'MIN', desc: 'Mina' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'NUK', desc: 'Instalação Nuclear' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'QUR', desc: 'Pedreira' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'SEP', desc: 'Plataforma Marítma' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'TRN', desc: 'Estação de Trem' },
    { actor: 'BEV', actornv2: 'IND', actornv3: 'WRH', desc: 'Armazém' },

    { actor: 'BEV', actornv2: 'NRES', actornv3: 'XPL', desc: 'Depósito Explosivo/Inflamável' },

    { actor: 'BEV', actornv2: 'OFF', actornv3: 'GOV', desc: 'Prédio Governamental' },
    { actor: 'BEV', actornv2: 'OFF', actornv3: 'WRK', desc: 'Local de Trabalho/Fábrica' },

    { actor: 'BEV', actornv2: 'OTH', actornv3: 'ACC', desc: 'Propriedade com Acesso Controlado' },
    { actor: 'BEV', actornv2: 'OTH', actornv3: 'BDG', desc: 'Ponte' },
    { actor: 'BEV', actornv2: 'OTH', actornv3: 'SUB', desc: 'Subúrbio' },
    { actor: 'BEV', actornv2: 'OTH', actornv3: 'TUN', desc: 'Túnel' },
    { actor: 'BEV', actornv2: 'OTH', actornv3: 'URB', desc: 'Área Urbana' },
    { actor: 'BEV', actornv2: 'OTH', actornv3: 'VIL', desc: 'Vila' },

    { actor: 'BEV', actornv2: 'SHP', actornv3: 'MAL', desc: 'Shopping Comercial' },

    { actor: 'PPL', actornv2: 'CHD', actornv3: 'BAB', desc: 'Bebê (até 12 Meses)' },
    { actor: 'PPL', actornv2: 'CHD', actornv3: 'INF', desc: 'Infantil (entre 1 e 3 anos)' },
    { actor: 'PPL', actornv2: 'CHD', actornv3: 'CHILD', desc: 'Criança (entre 3 e 10 anos)' },
    { actor: 'PPL', actornv2: 'CHD', actornv3: 'YOUTH', desc: 'Jovem (de 13 anos à Idade Adulta)' },

    { actor: 'PPL', actornv2: 'GND', actornv3: 'FML', desc: 'Feminino' },
    { actor: 'PPL', actornv2: 'GND', actornv3: 'ML', desc: 'Masculino' },
    { actor: 'PPL', actornv2: 'GND', actornv3: 'UND', desc: 'Indeterminado Visualmente' },

    { actor: 'PPL', actornv2: 'HST', actornv3: 'PCF', desc: 'Protesto Pacífico com Possibilidade de Agressão' },
    { actor: 'PPL', actornv2: 'HST', actornv3: 'SUI', desc: 'Pessoa tentando Cometer Suicídio' },
    { actor: 'PPL', actornv2: 'HST', actornv3: 'THT', desc: 'Protestante Desarmado Agindo de Maneira Ameaçadora' },
    { actor: 'PPL', actornv2: 'HST', actornv3: 'WPN', desc: 'Protestante Armado Agindo de Maneira Ameaçadora' },

    { actor: 'PPL', actornv2: 'PRS', actornv3: 'CST', desc: 'Prisioneiro em Custódia' },
    { actor: 'PPL', actornv2: 'PRS', actornv3: 'ESC', desc: 'Prisioneiro Fugitivo' },
    { actor: 'PPL', actornv2: 'PRS', actornv3: 'HGS', desc: 'Prisioneiro com Grande Risco à Segurança' },

    { actor: 'PPL', actornv2: 'SNS', actornv3: 'ETH', desc: 'Sensitividade Étnica' },
    { actor: 'PPL', actornv2: 'SNS', actornv3: 'FOR', desc: 'Nacionalidade' },
    { actor: 'PPL', actornv2: 'SNS', actornv3: 'LAN', desc: 'Linguagem Preferida' },
    { actor: 'PPL', actornv2: 'SNS', actornv3: 'REL', desc: 'Sensitividade Religiosa' },
    { actor: 'PPL', actornv2: 'SNS', actornv3: 'VIP', desc: 'Realeza, Chefe de Estado' },

    { actor: 'PPL', actornv2: 'VLN', actornv3: 'BLD', desc: 'Pessoa Cega' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'DEF', desc: 'Pessoa Surda' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'DSB', desc: 'Pessoa Debilitada Fisicamente' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'ELD', desc: 'Pessoa Idosa (mais de 65 Anos' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'INJ', desc: 'Pessoa Ferida' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'LDF', desc: 'Pessoa com Dificuldade de Aprendizado' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'OBS', desc: 'Pessoa Obesa' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'PAT', desc: 'Paciente Médico' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'PGN', desc: 'Mulher Grávida' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'SLFPRS', desc: 'Self-Presenters ???' },
    { actor: 'PPL', actornv2: 'VLN', actornv3: 'UNC', desc: 'Pessoa Inconsciente' },

    { actor: 'VEH', actornv2: 'AIR', actornv3: 'AMR', desc: 'Aeronave com Militar Armado' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'FLBA', desc: 'Balão Flutuante' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'FRG', desc: 'Aeronave Freteira' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'FXBA', desc: 'Balão Fixado' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'GLD', desc: 'Planador' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'HEL', desc: 'Helicóptero' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'HVY', desc: 'Aeronave Capaz de de Suportar Cargas Pesadas' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'JET', desc: 'Veículo com Motor à Jato' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'LGT', desc: 'Aeronave Leve' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'MIL', desc: 'Aeronave Militar' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'ORD', desc: 'Munição' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'OTH', desc: 'Outro' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'PAS', desc: 'Aeronave com Passageiros' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'PRBA', desc: 'Balão com Motor' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'PST', desc: 'Fonte de Energia por Pistão' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'RKT', desc: 'Fonte de Energia por Foguete' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'SEA', desc: 'Aeronave Capaz de Pousar na Água' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'SNO', desc: 'Aeronave Capaz de Pousar na Neve' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'TNK', desc: 'Aeronave Capaz de Transportar Combustível' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'UAV', desc: 'Veículo Aereo Desarmado' },
    { actor: 'VEH', actornv2: 'AIR', actornv3: 'ULG', desc: 'Aeronave Ultraleve' },

    { actor: 'VEH', actornv2: 'OTH', actornv3: 'HILL', desc: 'Veículos para Colinas' },
    { actor: 'VEH', actornv2: 'OTH', actornv3: 'SNO', desc: 'Veículos para Neve' },

    { actor: 'VEH', actornv2: 'TRK', actornv3: 'ART', desc: 'Caminhão Articulado' },
    { actor: 'VEH', actornv2: 'TRK', actornv3: 'EXC', desc: 'Carga Expecional' },
    { actor: 'VEH', actornv2: 'TRK', actornv3: 'HZD', desc: 'Tanque de Caminhão com Carga Perigosa' },
    { actor: 'VEH', actornv2: 'TRK', actornv3: 'NHZ', desc: 'Tanque de Caminhão com Carga Não Perigosa' },
    { actor: 'VEH', actornv2: 'TRK', actornv3: 'NUK', desc: 'Carga Nuclear' },
    { actor: 'VEH', actornv2: 'TRK', actornv3: 'REF', desc: 'Caminhão Refrigerado' },
    { actor: 'VEH', actornv2: 'TRK', actornv3: 'UND', desc: 'Caminhão com Carga Não Identificada' },

    { actor: 'VEH', actornv2: 'TRN', actornv3: '3RL', desc: 'Terceiro Trilho de Eletricidade' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'DSL', desc: 'Trem Movido a Diesel' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'HZD', desc: 'Trem com Carga Perigosa' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'LOC', desc: 'Trem do Tipo Locomotiva' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'NHZ', desc: 'Trem com Carga Não Perigosa' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'NUK', desc: 'Trem com Carga Nuclear' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'OVH', desc: 'Trem Movido à Sobrecarga de Energia' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'PAS', desc: 'Trem com Passageiros' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'REF', desc: 'Trem com Carga Refrigerada' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'STM', desc: 'Trem Movido à Vapor' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'TRM', desc: 'Bondes e Ferrovias Leves' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'UDG', desc: 'Trem Subterrâneo' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'UND', desc: 'Trem com Carga Não Determinada' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'VIP', desc: 'Trem com Pessoal Muito Importantes' },
    { actor: 'VEH', actornv2: 'TRN', actornv3: 'VLT', desc: 'Trem Longo' },

    { actor: 'VEH', actornv2: 'VES', actornv3: 'AMB', desc: 'Ambulância' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'BOT', desc: 'Barco' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'CNO', desc: 'Canoa ou Kayak' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'CRG', desc: 'Cargo ???' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'DSL', desc: 'Movido a Diesel' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'FLO', desc: 'Embarcação Flutuando' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'FRY', desc: 'Balsa' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'HOV', desc: 'Aerodeslizador' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'HZD', desc: 'Transportando Carga Perigosa' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'JSK', desc: 'Jet Ski' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'LEI', desc: 'Lazer ???' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'LIS', desc: 'Inclinado para um Lado' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'MIL', desc: 'Militar' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'MPW', desc: 'Movido por Força Humana' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'NHZ', desc: 'Transportando Carga Não Perigosa' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'NUK', desc: 'Movido à Reator Nuclear' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'PAS', desc: 'Transportando Passageiros' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'POL', desc: 'Usado pela Polícias' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'PTL', desc: 'Movido por Petróleo' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'RSC', desc: 'Uado para Resgate' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'SAI', desc: 'Movido pelo Vento' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'SMB', desc: 'Submarino' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'SINK', desc: 'Embarcação Afundando' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'SPC', desc: 'Navio Prisional' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'STE', desc: 'Movido à Vapor' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'SUNK', desc: 'Embarcação Afundada' },
    { actor: 'VEH', actornv2: 'VES', actornv3: 'UNM', desc: 'Controlado Remotamente' },

    { actor: 'ANI', actornv2: 'CON', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'DEA', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'DGR', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'FRM', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'HRD', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'INJ', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'LIV', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'PET', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'PRO', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'SPC', actornv3: '999', desc: '...' },
    { actor: 'ANI', actornv2: 'WLD', actornv3: '999', desc: '...' },

    { actor: 'BEV', actornv2: 'RESDW', actornv3: '999', desc: '...' },
    { actor: 'BEV', actornv2: 'RESIN', actornv3: '999', desc: '...' },
    { actor: 'BEV', actornv2: 'RESINT', actornv3: '999', desc: '...' },

    { actor: 'PPL', actornv2: '1', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'ADU', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'CNT', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'CWD', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'DED', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'EVC', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'GRP', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'INT', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'OTH', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'VIO', actornv3: '999', desc: '...' },
    { actor: 'PPL', actornv2: 'WTN', actornv3: '999', desc: '...' },
    
    { actor: 'VEH', actornv2: 'ANI', actornv3: '999', desc: '...' },
    { actor: 'VEH', actornv2: 'BIC', actornv3: '999', desc: '...' },
    { actor: 'VEH', actornv2: 'CAR', actornv3: '999', desc: '...' },
    { actor: 'VEH', actornv2: 'EMG', actornv3: '999', desc: '...' },
    { actor: 'VEH', actornv2: 'MBK', actornv3: '999', desc: '...' },
    { actor: 'VEH', actornv2: 'MIL', actornv3: '999', desc: '...' }
  ]);
};
