
exports.seed = function (knex) {
  // Inserts seed entries
  return knex('egeo_subtype').insert([
    { type: 'AIR', subtype: 'COR', desc: 'Corredor Aéreo' },
    { type: 'AIR', subtype: 'FLDZ', desc: 'Zona de Aerodromo' },
    { type: 'AIR', subtype: 'LZ', desc: 'Zona e Pouso' },
    { type: 'AIR', subtype: 'NOFLZN', desc: 'Proibido Voar' },
    { type: 'AIR', subtype: 'PZ', desc: 'Zona de Recebimento' },
    { type: 'AIR', subtype: 'UAVASP', desc: 'Espaço Aéreo de Veículos Aéreos Não Tripulados' },

    { type: 'CMB', subtype: 'CZ', desc: 'Zona de Combate' },
    { type: 'CMB', subtype: 'DNGR', desc: 'Zona de Perigo' },
    { type: 'CMB', subtype: 'EXTZN', desc: 'Zona de Extração' },
    { type: 'CMB', subtype: 'IMPTPT', desc: 'Ponto de Impacto' },

    { type: 'DGR', subtype: 'BIO', desc: 'Área Biológica Contaminada' },
    { type: 'DGR', subtype: 'BOMB', desc: 'Área de Bomba' },
    { type: 'DGR', subtype: 'CBRNHZ', desc: 'Perigo, Área de CBRN ' },
    { type: 'DGR', subtype: 'CBRNRSD', desc: 'Detecção ou Amostra de CBRN Coletada' },
    { type: 'DGR', subtype: 'CHM', desc: 'Área Contaminada Quimicamente' },
    { type: 'DGR', subtype: 'HZD', desc: 'Área de Risco' },
    { type: 'DGR', subtype: 'MIND', desc: 'Área Minerada' },
    { type: 'DGR', subtype: 'NGA', desc: 'Área Não Trafegável' },
    { type: 'DGR', subtype: 'NGACIV', desc: 'Área Não Trafegável para Civís' },
    { type: 'DGR', subtype: 'NUKCNL', desc: 'Taxa de Dose Nuclear Linha de Contorno ???' },
    { type: 'DGR', subtype: 'OBSGEN', desc: 'Obstáculo em Geral' },
    { type: 'DGR', subtype: 'PRHBAR', desc: 'Área Proibida' },
    { type: 'DGR', subtype: 'RAD', desc: 'Área Radioativa' },
    { type: 'DGR', subtype: 'RADCLD', desc: 'Contorno Determinado por Radar de Nuvem Radioativa ???' },
    { type: 'DGR', subtype: 'RSTR', desc: 'Área Proibida' },
    { type: 'DGR', subtype: 'SGA', desc: 'Área com Dificuldade de Tráfego' },
    { type: 'DGR', subtype: 'SITKIL', desc: 'Área com Suposta Morte' },
    { type: 'DGR', subtype: 'UNXOD', desc: 'Área a ser Explodida' },

    { type: 'GEN', subtype: 'AOR', desc: 'Área de Responsabilidade' },
    { type: 'GEN', subtype: 'ASYGEN', desc: 'Área de Montagem, Geral ???' },
    { type: 'GEN', subtype: 'ASYSPL', desc: 'Área de Montagem, Fornecimento ???' },
    { type: 'GEN', subtype: 'BDYOR', desc: 'Área de Montagem, Fornecimento ???' },
    { type: 'GEN', subtype: 'BDYPOA', desc: 'Área Administrativa Política' },
    { type: 'GEN', subtype: 'BDYPT', desc: 'Limite em Ponto ???' },
    { type: 'GEN', subtype: 'CKPGEN', desc: 'Checkpoint ???' },
    { type: 'GEN', subtype: 'CNTPTL', desc: 'Ponto de Contato (Local de Fácil Identificação)' },
    { type: 'GEN', subtype: 'COLDZ', desc: 'Área Gelada' },
    { type: 'GEN', subtype: 'COMCKP', desc: 'Checkpoint de Comunicação' },
    { type: 'GEN', subtype: 'COMLOW', desc: 'Locais com Produção em Excesso de Agentes Químicos ???' },
    { type: 'GEN', subtype: 'COMMZ', desc: 'Zona de Comunicação' },
    { type: 'GEN', subtype: 'COMUP', desc: 'Locais com Produção em Excesso de Agentes Químicos ???' },
    { type: 'GEN', subtype: 'CONTAR', desc: 'Área de Controle' },
    { type: 'GEN', subtype: 'CORDON', desc: 'Perímetro de uma Área ou Setor de Resgate' },
    { type: 'GEN', subtype: 'CRDPNT', desc: 'Ponto de Cordenação' },
    { type: 'GEN', subtype: 'DIVRT', desc: 'Rotas para Evitar Áreas Problemáticas' },
    { type: 'GEN', subtype: 'DROPPT', desc: 'Drop Point' },
    { type: 'GEN', subtype: 'ENTPT', desc: 'Ponto de Entrada' },
    { type: 'GEN', subtype: 'EVENT', desc: 'Área de Evento' },
    { type: 'GEN', subtype: 'EXITPT', desc: 'Ponto de Saída' },
    { type: 'GEN', subtype: 'FWCTPT', desc: 'Forward Control Point' },
    { type: 'GEN', subtype: 'HOTZ', desc: 'Hot Zone' },
    { type: 'GEN', subtype: 'INCGRD', desc: 'Localização do Incidente' },
    { type: 'GEN', subtype: 'LA', desc: 'Área de Pouso' },
    { type: 'GEN', subtype: 'LIMARE', desc: 'Área com Acesso Limitado' },
    { type: 'GEN', subtype: 'LOCAT', desc: 'Localização do Incidente' },
    { type: 'GEN', subtype: 'MSR', desc: 'Rota de Fornecimento Principal' },
    { type: 'GEN', subtype: 'PSSGPT', desc: 'Ponto de Passagem' },
    { type: 'GEN', subtype: 'PTINT', desc: 'Ponto de Interesse' },
    { type: 'GEN', subtype: 'RCNSAR', desc: 'Reconhecimento da Área' },
    { type: 'GEN', subtype: 'RNDZPT', desc: 'Local Estabelecimento para Pré Planejamento Durante a Emergência' },
    { type: 'GEN', subtype: 'ROUTE', desc: 'Rota' },
    { type: 'GEN', subtype: 'SAFERT', desc: 'Rota Segura' },
    { type: 'GEN', subtype: 'SAFZ', desc: 'Zona de Segurança' },
    { type: 'GEN', subtype: 'SARPNT', desc: 'Ponto de Busca e Resgate' },
    { type: 'GEN', subtype: 'SEARAR', desc: 'Área de Procura' },
    { type: 'GEN', subtype: 'SPRINK', desc: 'Área de Risco Especial' },
    { type: 'GEN', subtype: 'STRTPT', desc: 'Ponto de Início de Rotade Veículos' },
    { type: 'GEN', subtype: 'SUPARE', desc: 'Área de Fornecimento' },
    { type: 'GEN', subtype: 'SUPPT', desc: 'Ponto de Fornecimento' },
    { type: 'GEN', subtype: 'TRSTRT', desc: 'Rota temporária' },
    { type: 'GEN', subtype: 'WARMZ', desc: 'Área de Descontaminação' }
  ]);
};
